common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/wit/imu"
    camera_topic: "/image_topic"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0  # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 6
    blind: 3

color_mapping:
    use_no_ekf_coloring: true
    K_camera: [766.38136,   0.     , 628.1358 ,
           0.     , 720.66146, 348.08063,
           0.     ,   0.     ,   1.     ]
    D_camera: [-0.327005, 0.077308, 0.000458, 0.002563, 0.000000]
    time_offset_lidar_to_camera: 0                # ms         # lidar to camera
    # extrinsic_R: [-0.00436301,-0.999976,-0.00546917,
    #               0.0435895,0.00527384,-0.999036,
    #               0.99904,-0.0045972,0.0435655]
    # extrinsic_R: [-0.00784346,-0.999926,-0.00927599,
    #               0.0250127,0.00907719,-0.999646,
    #               0.999656,-0.0080727,0.0249397]
    extrinsic_T: [-0.0912564,0.0806241,, -0.109172]          # lidar to camera

    extrinsic_R: [-0.00678679,   0.202001,0.979361 ,
                           -0.999977 ,-0.00147166  ,-0.0066261 ,
                           0.000102807 , -0.979384  ,  0.202006]

# -0.00678679,   -0.999977, 0.000102807,   0.0912564,
#          0.202001 ,-0.00147166  , -0.979384,  -0.0806241,
#          0.979361 , -0.0066261  ,  0.202006,    0.109172,
#                 0,           0 ,          0         ,  1


mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    90
    det_range:     450.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
