common:
    lid_topic:  "/iv_points"
    imu_topic:  "/wit/imu"
    camera_topic: "/image_topic"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 1710829964.338891 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 4                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 128
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 3            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 1

color_mapping:
    K_camera: [1316.61904,    0.     , 1290.0679 ,
            0.     ,  922.20371,  622.56544,
            0.     ,    0.     ,    1.     ]
    D_camera: [-0.007435, -0.006332, 0.000476, -0.001715, 0.000000]
    time_offset_lidar_to_camera: -1710829963.201701             # ms
    # extrinsic_T: [0.0028198, 0.00786107, 0.058676]          # lidar to camera
    # extrinsic_R: [ 0.0319679 ,   0.99939,    0.01404 ,
    #               -0.997833  ,0.0311036 , 0.0579777,
    #               0.0575056  ,-0.015863 ,  0.998219]
    # extrinsic_T: [-0.0028198, -0.00786107, -0.058676]          # CAMERA TO LIDAR ACTUALLY
    # extrinsic_R: [ 0.0319679 , -0.997833 ,  0.0575056,
    #               0.99939   ,  0.0311036, -0.015863 ,
    #               0.01404   ,  0.0579777,  0.998219  ]
    extrinsic_T: [-0.00307705, 0.0307564, 0.0010094]
    extrinsic_R: [ 0.0320461, -0.998609,   0.0418694,
                   0.99929  ,  0.031182,  -0.0211317,
                   0.0197968,  0.042517,   0.998899  ]


mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    120
    det_range:     200.0
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [ -0.348506, -0.012519, 0.193932]
    extrinsic_R: [ 0.012020, -0.004795,  0.999916,
                  -0.087665, -0.996143, -0.003723,
                   0.996077, -0.087613, -0.012394]
                      


publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
